import re
def fix_stats(f):
    with open(f, 'r') as file: c = file.read()
    c = c.replace('CuriosityItem(\"🔥\",', 'CuriosityItem(pls.dev.sushilog.R.drawable.rice,')
    c = c.replace('CuriosityItem(pls.dev.sushilog.R.drawable.rice, strings.caloriesApprox', 'CuriosityItem(pls.dev.sushilog.R.drawable.kcal, strings.caloriesApprox')
    c = c.replace('CuriosityItem(\"🐟\",', 'CuriosityItem(pls.dev.sushilog.R.drawable.sashimi,')
    c = c.replace('private fun CuriosityItem(iconId: Int, text: String, colors: SushiColors) {\\n    Row', 'private fun CuriosityItem(iconId: Int, text: String, colors: SushiColors) {\\n    Row')
    c = c.replace('Text(emoji, fontSize = 20.sp)', 'Icon(painter = androidx.compose.ui.res.painterResource(id = iconId), contentDescription = null, tint = androidx.compose.ui.graphics.Color.Unspecified, modifier = Modifier.size(20.dp))')
    c = c.replace('Icon(painter = androidx.compose.ui.res.painterResource(id = emoji),', 'Icon(painter = androidx.compose.ui.res.painterResource(id = iconId),')
    c = c.replace('fun Icon(painter = androidx.compose.ui.res.painterResource(id = getPieceIconId(id, customPieces)), contentDescription = null, tint = androidx.compose.ui.graphics.Color.Unspecified, modifier = Modifier.size(20.dp))\\nText(getPieceName(id, customPieces, strings), color = colors.onSurface, fontSize = 14.sp, fontWeight = FontWeight.Medium)', 'Icon(painter = androidx.compose.ui.res.painterResource(id = getPieceIconId(id, customPieces)), contentDescription = null, tint = androidx.compose.ui.graphics.Color.Unspecified, modifier = Modifier.size(20.dp))')
    with open(f, 'w') as file: file.write(c)
def fix_custom_pieces(f):
    with open(f, 'r') as file: c = file.read()
    c = c.replace('var expandedSessionId by remember { mutableStateOf<String?>(null) }', 'var expandedSessionId by remember { mutableStateOf<String?>(null) }')
    c = c.replace('var newIconId by remember { mutableStateOf(\"🍣\") }', 'var newIconId by remember { mutableStateOf(pls.dev.sushilog.R.drawable.nigiris) }')
    c = c.replace('var newIconId by remember { mutableStateOf(piece.iconId) }', 'var newIconId by remember { mutableStateOf(piece.iconId) }')
    c = c.replace('imageOptions: List<String>', 'imageOptions: List<Int>')
    c = c.replace('fun IconPicker(imageOptions: List<String>', 'fun IconPicker(imageOptions: List<Int>')
    with open(f, 'w') as file: file.write(c)
fix_stats('app/src/main/java/pls/dev/sushilog/ui/screens/StatsScreen.kt')
fix_custom_pieces('app/src/main/java/pls/dev/sushilog/ui/screens/CustomPiecesScreen.kt')
